//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class coordinator
    {
        public int idTeam { get; set; }
        public Nullable<int> idRegion { get; set; }
    
        public virtual region region { get; set; }
        public virtual teamPosition teamPosition { get; set; }
    }
}
