//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public int idEquipment { get; set; }
        public Nullable<int> idProfession { get; set; }
        public string equipmentName { get; set; }
        public string type { get; set; }
        public string description { get; set; }
    
        public virtual profession profession { get; set; }
    }
}
