//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class people
    {
        public int idPeople { get; set; }
        public string family { get; set; }
        public string name { get; set; }
        public string middleName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
    
        public virtual missingPeople missingPeople { get; set; }
    }
}
