//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class reason
    {
        public int idReason { get; set; }
        public string typeReason { get; set; }
        public string reason1 { get; set; }
        public Nullable<int> idDisaster { get; set; }
    
        public virtual disaster disaster { get; set; }
    }
}
