//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        public int idTeam { get; set; }
        public string teamName { get; set; }
        public Nullable<int> idDisaster { get; set; }
        public Nullable<int> idPeople { get; set; }
    
        public virtual disaster disaster { get; set; }
        public virtual missingPeople missingPeople { get; set; }
        public virtual teamPosition teamPosition { get; set; }
    }
}
