//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int idUser { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string family { get; set; }
        public string name { get; set; }
        public string middleName { get; set; }
        public Nullable<int> idProfession { get; set; }
        public Nullable<int> idTeam { get; set; }
    
        public virtual profession profession { get; set; }
        public virtual teamPosition teamPosition { get; set; }
    }
}
